package vn.asg.swim.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import vn.asg.swim.entity.GwAlert;
import vn.asg.swim.entity.Gwin;
import vn.asg.swim.entity.InboundStatus;
import vn.asg.swim.model.AmhsFeedback;
import vn.asg.swim.model.AmqpProperties;
import vn.asg.swim.repository.AmhsFeedbackRepository;
import vn.asg.swim.repository.GwinRepository;

import java.util.List;

/**
 * Xử lý phản hồi AMHS bay ngược về cho điện văn ITCU đã gửi ở chiều SWIM → AMHS.
 * <p>
 * Gộp bốn test case vào một luồng, vì với ITCU cả bốn đều cùng một việc: tra điện văn gốc, ghi
 * log, báo Control Position.
 * <ul>
 *   <li><b>CTSW114</b> (§4.4.1.3) — NDR: điện văn không giao được.</li>
 *   <li><b>CTSW113</b> (§4.4.7.3) — RN và NRN cho điện văn ưu tiên SS.</li>
 *   <li><b>CTSW014</b> (§4.4.7.2) — RN có điện văn gốc priority khác SS: từ chối.</li>
 *   <li><b>CTSW015</b> (§4.4.7.1) — RN không có điện văn gốc: lạc tuyến, lưu lại cho CP xử lý.</li>
 * </ul>
 * Phản hồi KHÔNG được chuyển sang môi trường SWIM (§2.2.1.1: "This interface shall not receive
 * IPNs, Reports or Probes"), nên Control Position là điểm đến duy nhất.
 * <p>
 * <b>ITCU không sinh AMHS report.</b> Việc phát DR/NDR ra đường truyền X.400 - kể cả NDR cho IPN
 * lạc tuyến của CTSW015 - do AMHS Component đảm nhiệm. Lớp này chỉ tra cứu, ghi log và báo CP.
 * <p>
 * <b>Điện văn gốc nằm ở {@code gwin}, không phải {@code gwout}.</b> §4.4.7.1 a) hỏi IPM chủ đề có
 * phải "previously generated by the information transfer and control unit" hay không — ITCU chỉ
 * dựng IPM ở chiều SWIM → AMHS.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class AmhsFeedbackService {

    private final AmhsFeedbackRepository feedbackRepository;
    private final GwinRepository gwinRepository;
    private final AlertService alertService;
    private final MessageConversionService conversionService;

    /**
     * Xử lý một phản hồi. Luôn báo Control Position kể cả khi không tra ra điện văn gốc — tiêu chí
     * chấm không kèm điều kiện "nếu tra được", và bỏ sót thì mất hẳn dấu vết.
     * <p>
     * Việc đánh dấu đã xử lý do scheduler làm bằng mốc {@code cp.id}, không ghi vào
     * {@code cp.status} vì cột đó là phân loại riêng của AMHS Component.
     */
    @Transactional
    public void processFeedback(AmhsFeedback feedback) {
        Gwin subject = findSubjectMessage(feedback);

        if (feedback.isReport()) {
            handleReport(feedback, subject);
        } else if (subject == null) {
            handleMisroutedIpn(feedback);
        } else if (!"SS".equalsIgnoreCase(atsPriorityOf(subject))) {
            handleNonSsPriority(feedback, subject);
        } else {
            handleValidIpn(feedback, subject);
        }

    }

    /**
     * Tra điện văn gốc trong {@code gwin}. Thứ tự khoá phụ thuộc loại phản hồi, vì hai loại được
     * sinh ra ở hai tầng khác nhau:
     * <ul>
     *   <li><b>DR/NDR</b> do MTA sinh — MTA không giải mã nội dung nên chỉ biết
     *       <b>MTS-Identifier</b>. Tra {@code mts_id} trước.</li>
     *   <li><b>RN/NRN</b> do người nhận sinh — đã mở nội dung ra đọc nên biết
     *       <b>IPM-Identifier</b>. Tra {@code ipm_id} trước.</li>
     * </ul>
     * Vẫn thử nốt khoá còn lại làm dự phòng, phòng khi amss điền được cả hai.
     */
    private Gwin findSubjectMessage(AmhsFeedback feedback) {
        boolean preferMts = feedback.isReport();

        for (String key : new String[] {
                preferMts ? feedback.getSubjectMts() : feedback.getSubjectIpm(),
                preferMts ? feedback.getSubjectIpm() : feedback.getSubjectMts() }) {
            Gwin found = lookup(key, preferMts);
            if (found != null) {
                return found;
            }
        }
        return null;
    }

    /**
     * Tra một khoá, thử cả hai cột.
     * <p>
     * Không suy ra cột đích từ tên cột nguồn, vì chừng nào {@code cp.subjectMTS} chưa tồn tại thì
     * amss đặt MTS-Identifier vào chính {@code cp.subjectIPM} — quan sát được trên dữ liệu thật
     * ngày 07/09: dòng NDR mang khuôn MTS-Id {@code [/PRMD=...;gateway.attech.481-260907.084905]}
     * trong khi dòng RN mang khuôn IPM-Id (dấu sao ngăn giữa timestamp và O/R name), cả hai cùng
     * nằm ở một cột. Thử cả hai cột là hai lần tra có index, rẻ hơn nhiều so với đoán sai rồi coi
     * điện văn là lạc tuyến.
     *
     * @param preferMts thử {@code gwin.mts_id} trước hay {@code gwin.ipm_id} trước
     */
    private Gwin lookup(String key, boolean preferMts) {
        if (key == null || key.isBlank()) {
            return null;
        }
        String trimmed = key.trim();
        List<Gwin> rows = preferMts
                ? gwinRepository.findByMtsId(trimmed)
                : gwinRepository.findByIpmId(trimmed);
        if (rows.isEmpty()) {
            rows = preferMts
                    ? gwinRepository.findByIpmId(trimmed)
                    : gwinRepository.findByMtsId(trimmed);
        }
        return rows.isEmpty() ? null : rows.get(0);
    }

    /**
     * CTSW114 (§4.4.1.3) — báo cáo tầng vận chuyển.
     * <p>
     * NDR nghĩa là điện văn KHÔNG tới được người nhận, nên phải sửa lại trạng thái dòng
     * {@code gwin}: amss đặt trạng thái "đã giao" ngay khi bàn giao thành công cho MTA, mà NDR về
     * SAU thời điểm đó. Không sửa thì Control Position vĩnh viễn hiển thị một điện văn thất bại
     * là đã giao xong.
     * <p>
     * DR là tin tốt nên chỉ ghi log, không đụng vào trạng thái và không tạo cảnh báo.
     */
    private void handleReport(AmhsFeedback feedback, Gwin subject) {
        if (!AmhsFeedback.TYPE_NDR.equalsIgnoreCase(feedback.getIpnType())) {
            if (subject == null) {
                log.info("DR#{} không tra được điện văn gốc (mtsId={}) - bỏ qua",
                        feedback.getId(), feedback.getSubjectMts());
                return;
            }
            log.info("DR#{} xác nhận gwin#{} đã tới {}",
                    feedback.getId(), subject.getMsgid(), feedback.getRecipient());
            conversionService.logSwimToAmhs(subject.getMessageId(), subject.getOrigin(), "OK",
                    "dr_received: " + feedback.getRecipient(), null, subject.getIpmId());
            return;
        }

        String diagnostic = describeDiagnostic(feedback);

        if (subject == null) {
            log.warn("NDR#{} không tra được điện văn gốc (mtsId={} ipmId={}) - vẫn báo Control Position",
                    feedback.getId(), feedback.getSubjectMts(), feedback.getSubjectIpm());
            alertService.create(
                    GwAlert.TYPE_MESSAGE_DEAD, GwAlert.SEV_WARNING,
                    "NDR#" + feedback.getId() + " từ AMHS cho " + feedback.getRecipient()
                            + " (" + diagnostic + ") - không tra được điện văn gốc (mtsId="
                            + feedback.getSubjectMts() + "), cần Control Position xử lý (§4.4.1.3)",
                    "cp", feedback.getId());
            conversionService.logSwimToAmhs(null, feedback.getRecipient(), "REJECTED",
                    "ndr_received_orphan: " + diagnostic, "non-delivery-report",
                    feedback.getSubjectIpm());
            return;
        }

        log.warn("NDR#{} cho gwin#{}: điện văn không giao được tới {} ({})",
                feedback.getId(), subject.getMsgid(), feedback.getRecipient(), diagnostic);

        subject.setStatus(InboundStatus.FAILED.getValue());
        subject.setRejectionReason("non-delivery-report");
        subject.setRejectionDiagnostic(diagnostic);
        // Đặt SAU rejectionReason: setter của rejectionReason tự gán source = "SWIM" khi source
        // còn trống, mà lỗi này đến từ phía AMHS.
        subject.setRejectionSource("AMHS");
        gwinRepository.save(subject);

        alertService.create(
                GwAlert.TYPE_MESSAGE_DEAD, GwAlert.SEV_ERROR,
                "Điện văn gwin#" + subject.getMsgid() + " không giao được tới " + feedback.getRecipient()
                        + ": AMHS trả NDR (" + diagnostic + ") - báo Control Position (§4.4.1.3)",
                "gwin", subject.getMsgid());

        conversionService.logSwimToAmhs(subject.getMessageId(), subject.getOrigin(), "REJECTED",
                "ndr_received: " + feedback.getRecipient() + " - " + diagnostic,
                "non-delivery-report", subject.getIpmId());
    }

    /**
     * CTSW015 (§4.4.7.1) — RN có điện văn gốc không tồn tại: sinh NDR misrouted, log và lưu lại
     * để Control Position xử lý.
     */
    private void handleMisroutedIpn(AmhsFeedback feedback) {
        log.warn("IPN#{} ({}) lạc tuyến: không tìm thấy điện văn gốc ipmId={} mtsId={}",
                feedback.getId(), feedback.getIpnType(), feedback.getSubjectIpm(), feedback.getSubjectMts());

        alertService.create(
                GwAlert.TYPE_VALIDATION_ERROR, GwAlert.SEV_WARNING,
                "IPN#" + feedback.getId() + " (" + feedback.getIpnType() + ") từ " + feedback.getOrigin()
                        + " lạc tuyến: điện văn gốc (ipmId=" + feedback.getSubjectIpm()
                        + ") chưa từng đi qua gateway - cần Control Position xử lý (§4.4.7.1)",
                "cp", feedback.getId());

        // Việc phát NDR ra đường truyền X.400 do AMHS Component đảm nhiệm. Ở đây chỉ ghi lại
        // sự kiện để Control Position lưu trữ và xử lý - CTSW015 yêu cầu "Check the storage of
        // the RN for appropriate action at the Control Position".
        conversionService.logSwimToAmhs(null, feedback.getOrigin(), "REJECTED",
                "misrouted_ipn: " + feedback.getIpnType() + " ipmId=" + feedback.getSubjectIpm()
                        + " mtsId=" + feedback.getSubjectMts(),
                "misrouted-ipn", feedback.getSubjectIpm());
    }

    /**
     * CTSW014 điện văn 2 (§4.4.7.2) — điện văn gốc có priority khác "SS": RN bị từ chối, log và
     * báo Control Position, không sinh NDR.
     */
    private void handleNonSsPriority(AmhsFeedback feedback, Gwin subject) {
        String priority = atsPriorityOf(subject);
        log.warn("IPN#{} bị từ chối: điện văn gốc gwin#{} có priority {} khác SS (§4.4.7.2)",
                feedback.getId(), subject.getMsgid(), priority);

        alertService.create(
                GwAlert.TYPE_VALIDATION_ERROR, GwAlert.SEV_WARNING,
                "IPN#" + feedback.getId() + " (" + feedback.getIpnType() + ") bị từ chối: điện văn gốc "
                        + "gwin#" + subject.getMsgid() + " có priority " + priority
                        + " khác SS - lưu lại để Control Position xử lý (§4.4.7.2)",
                "cp", feedback.getId());

        conversionService.logSwimToAmhs(subject.getMessageId(), subject.getOrigin(), "REJECTED",
                "ipn_rejected_priority: " + priority + " (IPN#" + feedback.getId() + ")",
                "ipn-priority-not-ss", subject.getIpmId());
    }

    /**
     * CTSW113 và CTSW014 điện văn 1 (§4.4.7.3) — RN/NRN hợp lệ: log và báo Control Position.
     * <p>
     * NRN báo điện văn tới nơi nhưng KHÔNG được đọc, nên nâng mức cảnh báo lên WARNING để
     * operator không lướt qua giữa danh sách dài; RN là tin tốt nên để INFO.
     */
    private void handleValidIpn(AmhsFeedback feedback, Gwin subject) {
        boolean notRead = AmhsFeedback.TYPE_NRN.equalsIgnoreCase(feedback.getIpnType());
        log.info("IPN#{} ({}) hợp lệ cho điện văn gốc gwin#{} (priority SS) - báo Control Position",
                feedback.getId(), feedback.getIpnType(), subject.getMsgid());

        String detail = notRead
                ? " báo điện văn ưu tiên SS gwin#" + subject.getMsgid() + " tới nơi nhưng KHÔNG được đọc"
                        + reasonSuffix(feedback)
                : " xác nhận điện văn ưu tiên SS gwin#" + subject.getMsgid() + " đã được nhận";

        alertService.create(
                GwAlert.TYPE_VALIDATION_ERROR,
                notRead ? GwAlert.SEV_WARNING : GwAlert.SEV_INFO,
                "IPN#" + feedback.getId() + " (" + feedback.getIpnType() + ") từ " + feedback.getOrigin()
                        + detail + " (§4.4.7.3)",
                "cp", feedback.getId());

        conversionService.logSwimToAmhs(subject.getMessageId(), subject.getOrigin(),
                notRead ? "REJECTED" : "OK",
                "ipn_" + (notRead ? "non_receipt" : "accepted") + ": " + feedback.getIpnType()
                        + " từ " + feedback.getOrigin(),
                notRead ? "non-receipt-notification" : null,
                subject.getIpmId());
    }

    private String reasonSuffix(AmhsFeedback feedback) {
        if (feedback.getNonReceiptReason() != null) {
            return " (non-receipt-reason=" + feedback.getNonReceiptReason()
                    + (feedback.getDiscardReason() != null
                            ? ", discard-reason=" + feedback.getDiscardReason() : "") + ")";
        }
        return "";
    }

    /**
     * ATS-message-priority của điện văn gốc, phục vụ phép so "SS" của §4.4.7.2.
     * <p>
     * Ưu tiên cột {@code ats_priority}. Dòng {@code gwin} ghi trước migration 2026-09-06 còn NULL
     * nên suy lại từ AMQP priority theo §4.5.2.2 Table 9 (>=6 -> SS), thay vì mặc định coi là khác
     * SS — coi nhầm sẽ từ chối oan một RN hợp lệ.
     */
    private String atsPriorityOf(Gwin subject) {
        if (subject.getAtsPriority() != null && !subject.getAtsPriority().isBlank()) {
            return subject.getAtsPriority().trim().toUpperCase();
        }
        if (subject.getPriority() == null) {
            return null;
        }
        try {
            return AmqpProperties.mapPriorityToAmhs(subject.getPriority());
        } catch (IllegalArgumentException e) {
            log.warn("gwin#{} có AMQP priority {} ngoài dải 0-9, không suy được ATS priority",
                    subject.getMsgid(), subject.getPriority());
            return null;
        }
    }

    /**
     * Mô tả lỗi của NDR để đưa lên Control Position.
     * <p>
     * CTSW114 quy định NDR của nó mang {@code unable-to-transfer} cho reason-code và <b>để
     * TRỐNG</b> diagnostic-code. Nên rỗng là dữ liệu đúng chuẩn: thiếu diagnostic thì lùi về
     * reason-code, thiếu cả hai vẫn trả về nhãn có nghĩa chứ không để chuỗi rỗng lọt lên giao diện.
     */
    private String describeDiagnostic(AmhsFeedback feedback) {
        if (feedback.getDiagnosticCode() != null && !feedback.getDiagnosticCode().isBlank()) {
            return feedback.getDiagnosticCode().trim();
        }
        if (feedback.getReasonCode() != null && !feedback.getReasonCode().isBlank()) {
            return feedback.getReasonCode().trim();
        }
        return "unable-to-transfer";
    }

}
