package vn.asg.swim.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import vn.asg.swim.entity.GwAlert;
import vn.asg.swim.entity.Gwin;
import vn.asg.swim.entity.Gwout;
import vn.asg.swim.entity.McuIpn;
import vn.asg.swim.entity.OutboundStatus;
import vn.asg.swim.model.AmqpProperties;
import vn.asg.swim.repository.GwinRepository;
import vn.asg.swim.repository.GwoutRepository;
import vn.asg.swim.repository.McuIpnRepository;

import java.time.LocalDateTime;
import java.util.List;

/**
 * EUR Doc 047 §4.4.7 - Xử lý IPN (Receipt/Non-Receipt Notification) nhận từ AMHS.
 * <p>
 * Appendix A CTSW014, CTSW015 và CTSW113. IPN không được chuyển sang môi trường SWIM
 * (§2.2.1.1); ITCU kiểm tra rồi log và báo Control Position, hoặc sinh NDR nếu RN lạc tuyến.
 * <p>
 * <b>Bản tin chủ đề nằm ở gwin, không phải gwout.</b> §4.4.7.1 a) hỏi
 * "the subject IPM has been previously <i>generated by</i> the information transfer and control
 * unit" — ITCU chỉ dựng ra IPM ở chiều SWIM → AMHS. Chiều ngược lại nó nhận IPM từ AMHS rồi
 * chuyển sang AMQP, nên gwout.ipm_id là IPM do bên khác dựng. Cả ba test case đều mô tả
 * RN gửi tới IUT "addressing an AMQP consumer", tức bản tin gốc đi từ SWIM ra.
 * <p>
 * Ba nhánh theo §4.4.7.1 - §4.4.7.3:
 * <ol>
 *   <li><b>Không tìm thấy bản tin chủ đề</b> (§4.4.7.1) - RN lạc tuyến: sinh NDR
 *       {@code invalid-arguments} kèm supplementary-information, log và báo Control Position.</li>
 *   <li><b>Tìm thấy nhưng priority khác "SS"</b> (§4.4.7.2) - từ chối: log và báo Control
 *       Position để xử lý thủ công, không sinh NDR.</li>
 *   <li><b>Tìm thấy và priority là "SS"</b> (§4.4.7.3) - RN hợp lệ: log và báo Control Position.</li>
 * </ol>
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class IpnProcessingService {

    private final McuIpnRepository ipnRepository;
    private final GwinRepository gwinRepository;
    private final GwoutRepository gwoutRepository;
    private final ReportService reportService;
    private final AlertService alertService;
    private final MessageConversionService conversionService;

    /**
     * Xử lý một IPN đến. Bản ghi luôn được đánh dấu PROCESSED để không lặp lại,
     * kể cả khi bị từ chối — Control Position vẫn tra cứu được qua alert và traffic log.
     */
    @Transactional
    public void processIpn(McuIpn ipn) {
        Gwin subject = findSubjectMessage(ipn);

        if (subject == null) {
            handleMisroutedIpn(ipn);
        } else if (!"SS".equalsIgnoreCase(atsPriorityOf(subject))) {
            handleNonSsPriority(ipn, subject);
        } else {
            handleValidRn(ipn, subject);
        }

        ipn.setStatus(McuIpn.STATUS_PROCESSED);
        ipnRepository.save(ipn);
    }

    /**
     * §4.4.7.1 a) - bản tin chủ đề đã được ITCU sinh ra trước đó hay chưa.
     * Ưu tiên IPM-Identifier, dự phòng bằng MTS-Identifier.
     */
    private Gwin findSubjectMessage(McuIpn ipn) {
        if (isUsable(ipn.getSubjectIpmId())) {
            List<Gwin> byIpm = gwinRepository.findByIpmId(ipn.getSubjectIpmId().trim());
            if (!byIpm.isEmpty()) {
                return byIpm.get(0);
            }
        }
        if (isUsable(ipn.getSubjectMtsId())) {
            List<Gwin> byMts = gwinRepository.findByMtsId(ipn.getSubjectMtsId().trim());
            if (!byMts.isEmpty()) {
                return byMts.get(0);
            }
        }
        return null;
    }

    /**
     * ATS-message-priority của bản tin chủ đề, phục vụ phép so "SS" của §4.4.7.2.
     * <p>
     * Ưu tiên cột {@code ats_priority} ITCU đã ghi sẵn lúc nhận bản tin AMQP. Với các dòng
     * {@code gwin} có từ trước migration 2026-09-06 thì cột đó còn NULL, nên suy lại từ AMQP
     * priority theo §4.5.2.2 Table 9 (>=6 -> SS) thay vì mặc định coi là khác SS — coi nhầm sẽ
     * từ chối oan một RN hợp lệ.
     */
    private String atsPriorityOf(Gwin subject) {
        if (isUsable(subject.getAtsPriority())) {
            return subject.getAtsPriority().trim().toUpperCase();
        }
        if (subject.getPriority() == null) {
            return null;
        }
        try {
            return AmqpProperties.mapPriorityToAmhs(subject.getPriority());
        } catch (IllegalArgumentException e) {
            log.warn("gwin#{} có AMQP priority {} ngoài dải 0-9, không suy được ATS priority",
                    subject.getMsgid(), subject.getPriority());
            return null;
        }
    }

    /**
     * CTSW015 (§4.4.7.1) - RN có bản tin chủ đề không tồn tại: sinh NDR misrouted,
     * log và lưu lại để Control Position xử lý.
     */
    private void handleMisroutedIpn(McuIpn ipn) {
        log.warn("IPN#{} ({}) lạc tuyến: không tìm thấy bản tin chủ đề ipmId={} mtsId={}",
                ipn.getId(), ipn.getNotificationType(), ipn.getSubjectIpmId(), ipn.getSubjectMtsId());

        alertService.create(
                GwAlert.TYPE_VALIDATION_ERROR, GwAlert.SEV_WARNING,
                "IPN#" + ipn.getId() + " (" + ipn.getNotificationType() + ") từ " + ipn.getOrAddress()
                        + " lạc tuyến: bản tin chủ đề (ipmId=" + ipn.getSubjectIpmId()
                        + ") chưa từng đi qua gateway - cần Control Position xử lý (§4.4.7.1)",
                "mtcu_ipn", ipn.getId());

        // NDR đi qua cùng hàng đợi gwout_report, mà gwout_report.gwout_id có khoá ngoại
        // fk_report_gwout trỏ về gwout(msgid). Trước đây chỗ này dựng một Gwout tạm trong bộ nhớ
        // với msgid = mtcu_ipn.id — một giá trị KHÔNG thuộc không gian id của gwout — nên INSERT
        // luôn vi phạm khoá ngoại, ReportService nuốt lỗi và NDR của CTSW015 mất im lặng.
        //
        // Vì vậy phải GHI THẬT một dòng gwout cho sự kiện IPN lạc tuyến. Mọi cột gwout đều
        // nullable trừ msgid nên chi phí không đáng kể, và amss không phải đổi gì: vẫn đọc
        // gwout_report và gom theo gwout_id như với mọi bản tin khác.
        //
        // Dòng placeholder nằm ở gwout CHỈ VÌ hàng đợi phát NDR gắn khoá ngoại vào đó. Nó không
        // liên quan tới việc tra bản tin chủ đề — việc đó đã chuyển sang gwin cho đúng chiều.
        Gwout placeholder = new Gwout();
        // amhsid để NULL: ràng buộc uk_gwout_amhsid không cho hai IPN lạc tuyến cùng subject
        // MTS-Id cùng tồn tại. MTS-Id vẫn xuống tới amss qua tham số của recordNdr bên dưới.
        placeholder.setOrigin(ipn.getOrAddress());
        placeholder.setAddress(ipn.getOrAddress());
        placeholder.setTime(LocalDateTime.now());
        placeholder.setStatus(OutboundStatus.FAILED.getValue());
        placeholder.setRejectionSource("AMHS");
        placeholder.setRejectionReason("misrouted-ipn");
        placeholder.setRejectionDiagnostic("invalid-arguments");
        gwoutRepository.saveAndFlush(placeholder);

        reportService.recordNdr(placeholder.getMsgid(), ipn.getSubjectMtsId(), ipn.getOrAddress(),
                "invalid-arguments", "unable to notify RN to SWIM due to misrouted RN");
        // Traffic log giữ đủ subject IPM-Id / MTS-Id để Control Position tra ngược được,
        // dù hai cột tương ứng trên dòng gwout placeholder cố tình để NULL.
        conversionService.logAmhsToSwim(placeholder, null, "REJECTED",
                "ndr_misrouted_ipn: " + ipn.getNotificationType() + " ipmId=" + ipn.getSubjectIpmId(),
                ipn.getSubjectMtsId(), ipn.getSubjectIpmId(),
                "invalid-arguments", "unable to notify RN to SWIM due to misrouted RN");
    }

    /**
     * CTSW014 (điện văn 2, §4.4.7.2) - bản tin chủ đề có priority khác "SS": RN bị từ chối,
     * log và báo Control Position, không sinh NDR.
     */
    private void handleNonSsPriority(McuIpn ipn, Gwin subject) {
        String priority = atsPriorityOf(subject);
        log.warn("IPN#{} bị từ chối: bản tin chủ đề gwin#{} có priority {} khác SS (§4.4.7.2)",
                ipn.getId(), subject.getMsgid(), priority);

        alertService.create(
                GwAlert.TYPE_VALIDATION_ERROR, GwAlert.SEV_WARNING,
                "IPN#" + ipn.getId() + " (" + ipn.getNotificationType() + ") bị từ chối: bản tin chủ đề "
                        + "gwin#" + subject.getMsgid() + " có priority " + priority
                        + " khác SS - lưu lại để Control Position xử lý (§4.4.7.2)",
                "mtcu_ipn", ipn.getId());

        conversionService.logSwimToAmhs(subject.getMessageId(), subject.getOrigin(), "REJECTED",
                "ipn_rejected_priority: " + priority + " (IPN#" + ipn.getId() + ")",
                "ipn-priority-not-ss", subject.getIpmId());
    }

    /**
     * CTSW014 (điện văn 1, §4.4.7.3) và CTSW113 - RN/NRN hợp lệ: không bị từ chối, được log và
     * báo Control Position. IPN không chuyển sang SWIM (§2.2.1.1).
     */
    private void handleValidRn(McuIpn ipn, Gwin subject) {
        log.info("IPN#{} hợp lệ cho bản tin chủ đề gwin#{} (priority SS) - báo Control Position",
                ipn.getId(), subject.getMsgid());

        alertService.create(
                GwAlert.TYPE_VALIDATION_ERROR, GwAlert.SEV_INFO,
                "IPN#" + ipn.getId() + " (" + ipn.getNotificationType() + ") từ " + ipn.getOrAddress()
                        + " xác nhận bản tin ưu tiên SS gwin#" + subject.getMsgid()
                        + " đã được nhận (§4.4.7.3)",
                "mtcu_ipn", ipn.getId());

        conversionService.logSwimToAmhs(subject.getMessageId(), subject.getOrigin(), "OK",
                "ipn_accepted: " + ipn.getNotificationType() + " từ " + ipn.getOrAddress(),
                null, subject.getIpmId());
    }

    private boolean isUsable(String value) {
        return value != null && !value.isBlank();
    }
}
