spring.application.name=gateway-swim

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://192.168.22.163:3306/asg_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Server port
server.port=${SERVER_PORT:8082}

# Logging
logging.level.vn.asg=${LOG_LEVEL_ASG:DEBUG}
logging.level.org.apache.qpid=${LOG_LEVEL_QPID:WARN}
logging.level.com.ulisesbocchio=WARN
logging.level.org.springframework=INFO
logging.level.org.hibernate=WARN
logging.level.org.apache.tomcat=WARN
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Encoding
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.jpa.properties.hibernate.connection.charSet=UTF-8

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# AMQP Default Configurations (Required if DB accounts table is empty)
amqp.default.host=${AMQP_HOST:127.0.0.1}
amqp.default.port=${AMQP_PORT:5672}
amqp.default.username=${AMQP_USER:admin}
amqp.default.password=${AMQP_PASS:admin}


