package vn.asg.swim.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;
import vn.asg.swim.entity.GwAlert;
import vn.asg.swim.entity.Gwin;
import vn.asg.swim.entity.Gwout;
import vn.asg.swim.entity.McuIpn;
import vn.asg.swim.repository.GwinRepository;
import vn.asg.swim.repository.GwoutRepository;
import vn.asg.swim.repository.McuIpnRepository;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

/**
 * EUR Doc 047 §4.4.7 - xử lý IPN đến từ AMHS (Appendix A CTSW014, CTSW015, CTSW113).
 * <p>
 * Bản tin chủ đề của IPN nằm ở gwin chứ không phải gwout: §4.4.7.1 a) nói về IPM
 * "previously generated by the ITCU", mà ITCU chỉ dựng IPM ở chiều SWIM sang AMHS.
 */
@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
class IpnProcessingServiceTest {

    @Mock private McuIpnRepository ipnRepository;
    @Mock private GwinRepository gwinRepository;
    @Mock private GwoutRepository gwoutRepository;
    @Mock private ReportService reportService;
    @Mock private AlertService alertService;
    @Mock private MessageConversionService conversionService;

    @InjectMocks
    private IpnProcessingService service;

    private McuIpn ipn;

    @BeforeEach
    void setUp() {
        ipn = new McuIpn();
        ipn.setId(7L);
        ipn.setNotificationType(McuIpn.TYPE_RN);
        ipn.setSubjectIpmId("IPM-SS-001");
        ipn.setOrAddress("VVHHZTZX");

        when(gwinRepository.findByIpmId(anyString())).thenReturn(List.of());
        when(gwinRepository.findByMtsId(anyString())).thenReturn(List.of());
    }

    private Gwin subjectWithPriority(String priority) {
        Gwin subject = new Gwin();
        subject.setMsgid(500L);
        subject.setMessageId("amqp-msg-500");
        subject.setIpmId("IPM-SS-001");
        subject.setOrigin("VVTSSWIM");
        subject.setAtsPriority(priority);
        return subject;
    }

    @Test
    @DisplayName("CTSW014 điện văn 1: bản tin chủ đề priority SS -> chấp nhận, báo Control Position")
    void testCTSW014_SubjectWithSsPriority_ShouldBeAcceptedAndReported() {
        // §4.4.7.3: RN hợp lệ, không bị từ chối, được log và báo Control Position
        when(gwinRepository.findByIpmId("IPM-SS-001")).thenReturn(List.of(subjectWithPriority("SS")));

        service.processIpn(ipn);

        verify(alertService).create(anyString(), eq(GwAlert.SEV_INFO), contains("đã được nhận"),
                eq("mtcu_ipn"), eq(7L));
        verify(conversionService).logSwimToAmhs(eq("amqp-msg-500"), eq("VVTSSWIM"), eq("OK"),
                contains("ipn_accepted"), isNull(), eq("IPM-SS-001"));
        // RN hợp lệ không sinh NDR
        verify(reportService, never()).recordNdr(anyLong(), any(), anyString(), anyString(), anyString());
        assertEquals(McuIpn.STATUS_PROCESSED, ipn.getStatus());
    }

    @Test
    @DisplayName("CTSW014 điện văn 2: priority DD khác SS -> từ chối, KHÔNG sinh NDR")
    void testCTSW014_SubjectWithNonSsPriority_ShouldBeRejectedWithoutNdr() {
        when(gwinRepository.findByIpmId("IPM-SS-001")).thenReturn(List.of(subjectWithPriority("DD")));

        service.processIpn(ipn);

        verify(alertService).create(anyString(), eq(GwAlert.SEV_WARNING), contains("khác SS"),
                eq("mtcu_ipn"), eq(7L));
        verify(conversionService).logSwimToAmhs(eq("amqp-msg-500"), eq("VVTSSWIM"), eq("REJECTED"),
                contains("ipn_rejected_priority"), anyString(), eq("IPM-SS-001"));
        verify(reportService, never()).recordNdr(anyLong(), any(), anyString(), anyString(), anyString());
        assertEquals(McuIpn.STATUS_PROCESSED, ipn.getStatus());
    }

    @Test
    @DisplayName("Bản tin chủ đề phải tra ở gwin, không được tra gwout")
    void testSubjectLookupMustUseGwinNotGwout() {
        when(gwinRepository.findByIpmId("IPM-SS-001")).thenReturn(List.of(subjectWithPriority("SS")));

        service.processIpn(ipn);

        verify(gwinRepository).findByIpmId("IPM-SS-001");
        verify(gwoutRepository, never()).saveAndFlush(any());
    }

    @Test
    @DisplayName("gwin chưa có ats_priority suy lại từ AMQP priority")
    void testPriorityFallbackForRowsWithoutAtsPriority() {
        Gwin legacy = subjectWithPriority(null);
        legacy.setPriority((byte) 6);
        when(gwinRepository.findByIpmId("IPM-SS-001")).thenReturn(List.of(legacy));

        service.processIpn(ipn);

        verify(alertService).create(anyString(), eq(GwAlert.SEV_INFO), contains("đã được nhận"),
                eq("mtcu_ipn"), eq(7L));
    }

    @Test
    @DisplayName("CTSW015: bản tin chủ đề hư cấu -> NDR invalid-arguments kèm supplementary")
    void testCTSW015_NoSubjectMessage_ShouldGenerateMisroutedNdr() {
        ipn.setSubjectIpmId("IPM-KHONG-TON-TAI");

        service.processIpn(ipn);

        // gwout_report.gwout_id có khoá ngoại trỏ về gwout(msgid), nên phải GHI THẬT một dòng
        // gwout cho sự kiện IPN lạc tuyến rồi mới xếp NDR - dùng đối tượng Gwout tạm trong bộ nhớ
        // sẽ khiến INSERT vi phạm khoá ngoại và NDR mất im lặng.
        ArgumentCaptor<Gwout> captor = ArgumentCaptor.forClass(Gwout.class);
        verify(gwoutRepository).saveAndFlush(captor.capture());
        Gwout placeholder = captor.getValue();
        // NDR gửi về chính bên đã phát RN
        assertEquals("VVHHZTZX", placeholder.getAddress());
        assertEquals("misrouted-ipn", placeholder.getRejectionReason());
        // amhsid để NULL vì vướng ràng buộc uk_gwout_amhsid
        assertNull(placeholder.getAmhsid());

        // MTS-Identifier của bản tin chủ đề vẫn phải xuống tới amss để dựng NDR
        verify(reportService).recordNdr(placeholder.getMsgid(), ipn.getSubjectMtsId(), "VVHHZTZX",
                "invalid-arguments", "unable to notify RN to SWIM due to misrouted RN");

        verify(alertService).create(anyString(), eq(GwAlert.SEV_WARNING), contains("lạc tuyến"),
                eq("mtcu_ipn"), eq(7L));
        verify(conversionService).logAmhsToSwim(eq(placeholder), isNull(), eq("REJECTED"),
                contains("ndr_misrouted_ipn"), eq(ipn.getSubjectMtsId()), eq("IPM-KHONG-TON-TAI"),
                eq("invalid-arguments"), eq("unable to notify RN to SWIM due to misrouted RN"));
        assertEquals(McuIpn.STATUS_PROCESSED, ipn.getStatus());
    }

    @Test
    @DisplayName("Thiếu IPM-Identifier thì lùi về MTS-Identifier")
    void testFallbackToMtsIdentifier_WhenIpmIdMissing() {
        ipn.setSubjectIpmId(null);
        ipn.setSubjectMtsId("MTS-SS-001");
        when(gwinRepository.findByMtsId("MTS-SS-001")).thenReturn(List.of(subjectWithPriority("SS")));

        service.processIpn(ipn);

        verify(alertService).create(anyString(), eq(GwAlert.SEV_INFO), anyString(), anyString(), anyLong());
        verify(gwoutRepository, never()).saveAndFlush(any());
    }

    @Test
    @DisplayName("Mọi nhánh đều phải đánh dấu PROCESSED để không xử lý lặp")
    void testProcessedFlag_ShouldAlwaysBePersisted() {
        service.processIpn(ipn);

        verify(ipnRepository).save(ipn);
        assertEquals(McuIpn.STATUS_PROCESSED, ipn.getStatus());
    }
}
